server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://{}:3306/springboot_mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver