server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_shiro?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 654321
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
    cache: false